# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Pose.destroy_all
Exercise.destroy_all

# h = Hiit.create(name:"HIIT", description:"High Intensity Interval Training", image:"https://lmimirror3pvr.azureedge.net/static/media/12419/f550bcca-c76d-420c-999f-d6ba1fa41b46/hiit_960x540-v2.jpg")
# y = Yoga.create(name:"Yoga", description:"Improve your posture, balance, and coordination", image:"https://specials-images.forbesimg.com/imageserve/1067864612/960x0.jpg?fit=scale")

Exercise.create(name:"Situps", description:"lie flat on your back, knees bent, lift your torso to a seated position, and then lie flat again without changing the position of your legs", category: "Abs", image:"https://media1.popsugar-assets.com/files/thumbor/NpWpiaoZCsPWiImEqasGpeO-uXY/fit-in/1024x1024/filters:format_auto-!!-:strip_icc-!!-/2014/03/17/884/n/1922729/79bc07ee5cb226ab_woman-doing-sit-ups/i/Core-Full-Sit-Ups.jpg")
Exercise.create(name:"Reverse Crunches", description:"Lie on your back with your knees together and your legs bent then lift your hips off the floor as you crunch your knees inward to your chest.", category: "Abs", image:"https://cdn2.coachmag.co.uk/sites/coachmag/files/styles/insert_main_wide_image/public/images/dir_7/mens_fitness_3912.jpg?itok=5GNjDrls")
Exercise.create(name:"Bicycles", description:"Lie flat on the floor. Put your hands behind your head, then bring your knees in towards your chest and lift your shoulder blades off the ground. Straighten your right leg while turning your upper body to the left, bringing your right elbow towards the left knee.Then switch sides back and forth", category: "Abs", image:"https://media1.popsugar-assets.com/files/thumbor/7RryBm3ZNBY7F3vwor1VcYiFrMw/fit-in/1024x1024/filters:format_auto-!!-:strip_icc-!!-/2016/12/16/640/n/1922729/1f8b623f8d7f01f9_bicycle-crunch/i/Tabata-5-Bicycle-Crunch.jpg")
Exercise.create(name:"Flutter Kicks", description:"Lie on your back and use your core to “flutter” your legs up and down", category: "Abs", image:"https://cdn.prod.openfit.com/uploads/2019/05/29183252/flutter-kicks-exercise-woman.jpg")
Exercise.create(name:"Leg Raises", description:"Lie on your back with your legs straight out in front of you. Keep your knees straight and raise your legs by flexing the hips until they are completely flexed.", category: "Abs", image:"http://momfabfun.com/wp-content/uploads/2013/03/legraises_600x400.jpg")
Exercise.create(name:"Plank", description:"Place your hands directly under your shoulders. Step your feet back, hip-distance apart. Maintain a straight line from heels through the top of your head, looking down at the floor. Tighten your abs, quads, glutes, and hold.", category: "Abs", image:"https://media1.popsugar-assets.com/files/thumbor/nbl_ojC5HoU2jPWoYAGGoVVHKtE/fit-in/1024x1024/filters:format_auto-!!-:strip_icc-!!-/2018/10/19/911/n/1922729/netimgWjZXXt/i/Core-Series.jpg")
Exercise.create(name:"Forward Lunges", description:"Take a big step forward with left or right leg. Lower your body until right thigh is parallel to the floor and shin is vertical. Knee should not goes past toe. Press into heel to drive back up to starting position.", category: "Legs and Glutes", image:"https://twohundredlunges.com/new-site/wp-content/uploads/2019/03/Fotolia_52440426_S.jpg")
Exercise.create(name:"Squats", description:"Place your feet shoulder-width apart or slightly wider. Sit back and down like you're sitting into an imaginary chair. Lower down so your thighs are parallel to the floor putting your weight into your heels.Then push through your heels to bring yourself back to the starting position.", category: "Legs and Glutes", image:"https://media.self.com/photos/57da2eaa46d0cb351c8c7ebc/master/w_1600%2Cc_limit/correct-squat_feat.jpg")
Exercise.create(name:"Donkey Kicks", description:"Position your hands underneath your shoulders and place your knees under your hips. Keep your right knee bent at 90 degrees and flex the foot as you lift the knee until it is level with the hip. Lower the knee without touching the floor and repeat the lift.", category: "Legs and Glutes", image:"https://media1.popsugar-assets.com/files/thumbor/vfDC_62gfqVWl7gqtfBX6FrXd60/fit-in/1024x1024/filters:format_auto-!!-:strip_icc-!!-/2015/04/02/857/n/1922729/edf9480e2d4d09ab_Donkey-Kick/i/Donkey-Kicks.jpg")
Exercise.create(name:"Glute Bridge", description:"Lie on the floor, with your knees bent and feet flat on the ground. Keep your arms at your side with your palms down. Lift your hips off the ground until your knees, hips and shoulders form a straight line. Hold your bridged position for a couple of seconds before easing back down.", category: "Legs and Glutes", image:"https://media1.popsugar-assets.com/files/thumbor/_ExGECryIsUCyQmGaWRCUwzKe9g/fit-in/1024x1024/filters:format_auto-!!-:strip_icc-!!-/2018/09/21/987/n/1922729/58137b36f73a4eb3_bridge_marching_1/i/Glute-Bridge.jpg")
Exercise.create(name:"Pushups", description:"Start in plank position and lower your body until your chest nears the floor at the bottom of the movement, and then return up to the starting position. ", category: "Arms", image:"https://media1.popsugar-assets.com/files/thumbor/kpEya4_8eFp3qCFfe96JhbcAzZg/fit-in/1024x1024/filters:format_auto-!!-:strip_icc-!!-/2018/01/18/028/n/1922729/df3b7a4543fbbfb1_482d4566494adf6f_8589c22c445d63e2_0e7e9800cb65fd44_Tricep-Push-Up/i/Negative-Push-Ups.jpg")
Exercise.create(name:"Tricep dips", description:"Sit on the edge or bench or mat with your legs extended out in front of you. Straighten your arms, keeping a little bend in your elbows then slowly bend your elbows to lower your body toward the floor until your elbows are at about a 90-degree angle", category: "Arms", image:"https://media1.popsugar-assets.com/files/thumbor/Vl1O403i1KsKyScfEHW_Se8VOX0/fit-in/1024x1024/filters:format_auto-!!-:strip_icc-!!-/2014/04/25/773/n/1922729/71dfb70a7ef96be8_c58b14640c2032c6_triceps-dips.jpg.xxxlarge/i/Triceps-Dips.jpg")
Exercise.create(name:"Bicep curls", description:"Hold the weights facing up so the wrists, elbows, and shoulders are in a straight line about shoulder-width apart. Lift the weights toward the shoulders while bending the elbows. Slowly lower the weight to return to the starting position. ", category: "Arms", image:"https://media1.popsugar-assets.com/files/thumbor/CA4-8zm5VgM0l6f0ccu8I8BuS5I/fit-in/1024x1024/filters:format_auto-!!-:strip_icc-!!-/2015/03/10/605/n/1922729/570ff954_bicep-curls-Red/i/Bicep-Curl.jpg")
Exercise.create(name:"Shoulder press", description:"Bend your elbows and raise your upper arms to shoulder height so the dumbbells are at ear level. Push the dumbbells up and in until the ends of the dumbbells touch lightly, directly over your head, and then lower the dumbbells back to ear level.", category: "Arms", image:"https://media1.popsugar-assets.com/files/thumbor/hDSy9zXJMvWp2_eBvUbCJDmoiCk/fit-in/1024x1024/filters:format_auto-!!-:strip_icc-!!-/2016/03/31/793/n/1922729/1d82e978fdd9090e_Overhead-press/i/Overhead-Shoulder-Press.jpg")
Exercise.create(name:"Front Raises", description:"start with a dumbbell in each hand at thigh level. You raise the dumbbells parallel to the floor and then return to the starting position to complete one exercise repetition.", category: "Arms", image:"https://www.oxygenmag.com/.image/c_limit%2Ccs_srgb%2Cq_auto:good%2Cw_630/MTQ1MzQ3MzE1OTUxMTUwODY1/front-raise.webp")
Exercise.create(name:"Jumping Jacks", description:"Stand upright with your legs together, arms at your sides. Bend your knees slightly, and jump into the air. As you jump, spread your legs to be about shoulder-width apart. Stretch your arms out and over your head. Jump back to starting position", category: "Cardio", image:"https://media1.popsugar-assets.com/files/thumbor/NmhBTSP09YT_0iLhrGDTQUN1Mr0/fit-in/1024x1024/filters:format_auto-!!-:strip_icc-!!-/2015/05/01/974/n/1922729/8a48e47672d474dc_c9d6640d1d97a449_jumping-jacks.xxxlarge/i/Tabata-One-Jumping-Jack.jpg")
Exercise.create(name:"High Knees", description:"Stand with your feet hip-width apart. Lift up your left knee to your chest. Switch to lift your right knee to your chest. Continue the movement, alternating legs and moving at a sprinting or running pace.", category: "Cardio", image:"https://media1.popsugar-assets.com/files/thumbor/_0L2vq5jL5YXZP-GXopwgprLjOU/fit-in/1024x1024/filters:format_auto-!!-:strip_icc-!!-/2019/02/26/720/n/1922729/11d22cab33f367ac_4/i/Bonus-High-Knee-Oblique-Twist.jpg")
Exercise.create(name:"Butt Kicks", description:"Bring one heel off the floor toward your glutes. At the same time, match this movement with the opposite-side hand coming up towards your shoulder, like you’re running. Repeat this movement on the other side, again with the opposite arm coming up towards your shoulder.", category: "Cardio", image:"https://media1.popsugar-assets.com/files/thumbor/fJnX5rpJmIdfJmZA6Gvk8TDs0bw/fit-in/1024x1024/filters:format_auto-!!-:strip_icc-!!-/2014/10/14/918/n/1922729/62b8c8b0a7d9cb2a_Butt-Kickers/i/Butt-Kicks.jpg")
Exercise.create(name:"Speed Skaters", description:"From a normal standing position, take a big step out to the right. As you do, sweep your left leg behind you while bringing your left arm across your body. Then, step to the left, bringing your right leg behind you and your right arm across your body. Continue alternating sides.", category: "Cardio", image:"https://media1.popsugar-assets.com/files/thumbor/ySjtj2JZ6bIof9BdEb9sNJfSceg/fit-in/1024x1024/filters:format_auto-!!-:strip_icc-!!-/2018/10/19/932/n/1922729/ef711b5f5bca4b35849642.44129441_Side-Skater/i/Tabata-Four-Side-Skater.jpg")
Exercise.create(name:"Jump Squats", description:"Stand with your feet shoulder-width apart. Start by doing a regular squat, then engage your core and jump up explosively. When you land, lower your body back into the squat position.", category: "Cardio", image:"https://media1.popsugar-assets.com/files/thumbor/kNR2-3YVOfzzwmCyRCn7fhDsQPs/fit-in/2048xorig/filters:format_auto-!!-:strip_icc-!!-/2014/01/31/901/n/1922729/1545977b1743e558_Jump-Squat.jpg")

Pose.create(name:"Bridge Pose", description:"Lie on the floor, bend your knees and set your feet on the floor, heels as close to the sit bones as possible. Exhale and, press your inner feet and arms into the floor, push your tailbone upward and lift the buttocks off the floor.", category: "Level 1", image:"https://www.yogajournal.com/.image/c_limit%2Ccs_srgb%2Cq_auto:good%2Cw_860/MTQ3MTc0Njc5MDM4MTQxOTAy/2hp_286_0621_bjk.webp")
Pose.create(name:"Chair Pose Utkatasana", description:"From standing, Inhale and raise your arms perpendicular to the floor. Either keep the arms parallel, palms facing inward, or join the palms. Exhale and bend your knees, trying to take the thighs as nearly parallel to the floor as possible.", category: "Level 1", image:"https://www.yogajournal.com/.image/c_limit%2Ccs_srgb%2Cq_auto:good%2Cw_860/MTQ3MTUyNzM1MjQ1NDQ0NTU4/hp_292_267_bjk.webp")
Pose.create(name:"Upward-Facing Dog", description:"Lie on your stomach on the floor. Stretch your legs back, tops of the feet on the floor. Bend your elbows and spread your palms on the floor beside your waist so that your forearms are relatively perpendicular to the floor. Inhale and press your inner hands firmly into the floor and slightly back, as if you were trying to push yourself forward along the floor. Then straighten your arms and simultaneously lift your torso up and your legs a few inches off the floor on an inhalation.", category: "Level 1", image:"https://www.yogajournal.com/.image/c_limit%2Ccs_srgb%2Cq_auto:good%2Cw_860/MTQ3MTU3MjczOTUxNjEwMzE4/3yp_287_6710_gn_bjk.webp")
Pose.create(name:"Cat", description:"Start on your hands and knees in a tabletop position. Make sure your knees are set directly below your hips and your wrists, elbows and shoulders are in line and perpendicular to the floor. Center your head in a neutral position, eyes looking at the floor. As you exhale, round your spine toward the ceiling", category: "Level 1", image:"https://www.yogajournal.com/.image/c_limit%2Ccs_srgb%2Cq_auto:good%2Cw_860/MTQ3MTc0NjYxMzIxNDAxODA2/2hp_286_0574_bjk.webp")
Pose.create(name:"Savasana", description:"Inhale and slowly extend the right leg, then the left, pushing through the heels. Release both legs, softening the groins, and see that the legs are angled evenly relative to the mid-line of the torso, and that the feet turn out equally. Narrow the front pelvis and soften (but don't flatten) the lower back.", category: "Level 1", image:"https://www.yogajournal.com/.image/c_limit%2Ccs_srgb%2Cq_auto:good%2Cw_860/MTQ3MTU0OTQxNTE2MDY0NTU5/2hp_291_1982_gn_bjk.webp")
Pose.create(name:"Cow", description:"Start on your hands and knees in a tabletop position. Make sure your knees are set directly below your hips and your wrists, elbows and shoulders are in line and perpendicular to the floor. Center your head in a neutral position, eyes looking at the floor. As you inhale, lift your sitting bones and chest toward the ceiling, allowing your belly to sink toward the floor. Lift your head to look straight forward.", category: "Level 1", image:"https://www.yogajournal.com/.image/c_limit%2Ccs_srgb%2Cq_auto:good%2Cw_860/MTQ3MTU3MTAwMjczODcwMjg2/3hp_288_02_bjk2.webp")
Pose.create(name:"Head-to-Knee Forward Bend", description:"While seated, extend the right leg straight out in front of you, place the bottom of the left foot against the right thigh. Pull the right leg in to square the hips to the front wall. Inhale the arms up and reach out of the waist lengthening the spine. Keep the length as you exhale forward, bending the right knee enough to interlace the fingers around the foot and to place the head against the knee.", category: "Level 1", image:"https://www.yogajournal.com/.image/c_limit%2Ccs_srgb%2Cq_auto:good%2Cw_860/MTQ3MTUyNzM1NTEzNDg2Nzk4/yp_292_00990_bjk.webp")
Pose.create(name:"High Lunge", description:"From Downward-Facing Dog exhale and step your right foot forward between your hands, aligning your knee over the heel. Keep your left leg strong and firm. Inhale and raise your torso to upright. At the same time, sweep your arms wide to the sides and raise them overhead, palms facing.", category: "Level 1", image:"https://www.yogajournal.com/.image/c_limit%2Ccs_srgb%2Cq_auto:good%2Cw_860/MTQ3MTU3MTIzNjI3NzU0OTU4/3hp_288_07_bjk2.webp")
Pose.create(name:"Warrior I Pose", description:"Begin in Mountain Pose (Tadasana), standing with your feet hip-distance apart and your arms at your sides. Exhale as you step your feet wide apart, about 4 to 5 feet. Turn your right foot out 90 degrees, so your toes are pointing to the top of the mat. Pivot your left foot inwards at a 45-degree angle. Align your front heel with the arch of your back foot. Keep your pelvis turned toward the front of your mat. Press your weight through your left heel. Then, exhale as you bend your right knee over your right ankle. Your shin should be perpendicular to the floor.Reach up strongly through your arms. ", category: "Level 1", image:"https://www.yogajournal.com/.image/c_limit%2Ccs_srgb%2Cq_auto:good%2Cw_860/MTQ3MTU2NzE0MjYzNjg0OTEx/2yp_290_1642_bjk.webp")
Pose.create(name:"Warrior II Pose", description:"Stand in Tadasana (Mountain Pose). With an exhalation, step or lightly jump your feet 3 1/2 to 4 feet apart. Raise your arms parallel to the floor and reach them actively out to the sides, shoulder blades wide, palms down. Turn your right foot slightly to the right and your left foot out to the left 90 degrees. Align the left heel with the right heel. Firm your thighs and turn your left thigh outward so that the center of the left knee cap is in line with the center of the left ankle.", category: "Level 1", image:"https://www.yogajournal.com/.image/c_limit%2Ccs_srgb%2Cq_auto:good%2Cw_860/MTQ3MTU0OTQxNTE1OTMzNDg3/2hp_291_1870_gn_bjk.webp")
Pose.create(name:"Plank", description:"Start in Downward-Dog. Then inhale and draw your torso forward until the arms are perpendicular to the floor and the shoulders directly over the wrists, torso parallel to the floor.", category: "Level 1", image:"https://www.yogajournal.com/.image/c_limit%2Ccs_srgb%2Cq_auto:good%2Cw_860/MTQ3MTU0MjUyOTc4OTg4ODQ3/editplankhp2_292_37428_cmyk.webp")
Pose.create(name:"Side Plank", description:"Shift onto the outside edge of your left foot, and stack your right foot on top of the left. Now swing your right hand onto your right hip, turn your torso to the right as you do, and support the weight of your body on the outer left foot and left hand.", category: "Level 1", image:"https://www.yogajournal.com/.image/c_limit%2Ccs_srgb%2Cq_auto:good%2Cw_860/MTQ3MTc4MTA4ODM3OTYzNTY3/2hp_271_06_fnl.webp")
Pose.create(name:"Wild Thing", description:"Start in Downward-Facing Dog. Bring your weight into your right hand and roll onto the outer edge of your right foot like Side Plank Pose. On an inhalation, lift your hips with buoyancy. Stay strong in your right hand making a clawing action with the fingers. Keep the head of the right arm bone back. On an exhalations, step your left foot back and place your toes on the floor with your knee partially bent. Curl back through your upper back to create a sweeping action of the shoulder blades into the back of the rib cage.", category: "Level 1", image:"https://www.yogajournal.com/.image/c_limit%2Ccs_srgb%2Cq_auto:good%2Cw_860/MTQ3MTc3OTUzNDEzODM0MTkw/2yp_283_0205_fnl.webp")
Pose.create(name:"Crow", description:"Squat down from Tadasana with your inner feet a few inches apart. Separate your knees wider than your hips and lean the torso forward, between the inner thighs. Stretch your arms forward, then bend your elbows, place your hands on the floor and the backs of the upper arms against the shins. Lift up onto the balls of your feet and lean forward even more, taking the weight of your torso onto the backs of the upper arms.", category: "Level 1", image:"https://www.yogajournal.com/.image/c_limit%2Ccs_srgb%2Cq_auto:good%2Cw_860/MTQ3MTUyNzM1MjQ0OTg1ODA2/crowhp_292_9_bjk.webp")
Pose.create(name:"Eagle", description:"Stand in Tadasana. Bend your knees slightly, lift your left foot up and, balancing on your right foot, cross your left thigh over the right. Point your left toes toward the floor, press the foot back, and then hook the top of the foot behind the lower right calf. Balance on the right foot. Stretch your arms straight forward, parallel to the floor, and spread your scapulas wide across the back of your torso. Cross the arms in front of your torso so that the right arm is above the left, then bend your elbows. Snug the right elbow into the crook of the left, and raise the forearms perpendicular to the floor. The backs of your hands should be facing each other.", category: "Level 1", image:"https://www.yogajournal.com/.image/c_limit%2Ccs_srgb%2Cq_auto:good%2Cw_860/MTQ3MTUyNzM1MjQ1MDUxMzQy/eaglehp2_292_37370_cmyk.webp")
Pose.create(name:"Half Moon", description:"Exhale, press your right hand and right heel firmly into the floor, and straighten your right leg, simultaneously lifting the left leg parallel (or a little above parallel) to the floor.", category: "Level 1", image:"https://www.yogajournal.com/.image/c_limit%2Ccs_srgb%2Cq_auto:good%2Cw_860/MTQ3MTU0OTQxNTE2MTMwMDk1/2hp_291_1860_gn_bjk.webp")
Pose.create(name:"Supported Headstand", description:"Lace your fingers together and set the forearms on the floor, elbows at shoulder width. Roll the upper arms slightly outward, but press the inner wrists firmly into the floor. Set the crown of your head on the floor. Press the bases of your palms together and snuggle the back of your head against the clasped hands. Inhale and lift your knees off the floor. Carefully walk your feet closer to your elbows, heels elevated. Actively lift through the top thighs", category: "Level 1", image:"https://www.yogajournal.com/.image/c_limit%2Ccs_srgb%2Cq_auto:good%2Cw_860/MTQ3MTc4MDEyNDY5NjM0NTEw/2yp_281_0049_bjk.webp")
Pose.create(name:"Supported Shoulderstand", description:"Exhale, press your arms against the floor, and push your feet away from the floor, drawing your thighs into the front torso. Continue to lift by curling the pelvis and then the back torso away from the floor, so that your knees come toward your face. ", category: "Level 1", image:"https://www.yogajournal.com/.image/c_limit%2Ccs_srgb%2Cq_auto:good%2Cw_860/MTQ3MTc4MTM4NjM0Mjk5MTgz/2anatomy_284_05_fnl.webp")
Pose.create(name:"Camel Pose", description:"From Child’s pose, come up onto both knees, placing them hip width apart. Place the palms of the hands on the sacrum with the fingers pointed down. Inhale and press the knees down reaching the crown of the head up to lengthen the spine. Exhale and press the hips forward, squeezing the buttocks and thighs and supporting your weight with the arms as you bend backwards.", category: "Level 1", image:"https://www.yogajournal.com/.image/c_limit%2Ccs_srgb%2Cq_auto:good%2Cw_860/MTQ3MTU2ODg3NDA0NTU0MDMx/3enneagram_289_1349_bjk.webp")
Pose.create(name:"Wheel", description:"Lie on your stomach on the floor. Bend your knees and set your feet on the floor, heels as close to the sitting bones as possible. Bend your elbows and spread your palms on the floor beside your head, forearms relatively perpendicular to the floor, fingers pointing toward your shoulders. Pressing your inner feet actively into the floor, exhale and push your tailbone up, firming (but not hardening) the buttocks, and lift the buttocks off the floor.", category: "Level 1", image:"https://www.yogajournal.com/.image/c_limit%2Ccs_srgb%2Cq_auto:good%2Cw_860/MTQ3MTc4MDI4NTc1NzYyMjIz/2hp_276_13_fnl.webp")
Pose.create(name:"Child's Pose", description:"Kneel on the floor. Touch your big toes together and sit on your heels, then separate your knees about as wide as your hips. Exhale and lay your torso down between your thighs.", category: "Level 1", image:"https://www.yogajournal.com/.image/c_limit%2Ccs_srgb%2Cq_auto:good%2Cw_860/MTQ3MTU3MzE1MDIyMjM1NDM5/3yp_287_6604_gn_bjk.webp")
Pose.create(name:"Downward-Facing Dog", description:"Come onto the floor on your hands and knees. Set your knees directly below your hips and your hands slightly forward of your shoulders. Spread your palms, index fingers parallel or slightly turned out, and turn your toes under. Exhale and lift your knees away from the floor. At first keep the knees slightly bent and the heels lifted away from the floor. Lengthen your tailbone away from the back of your pelvis.", category: "Level 1", image:"https://www.yogajournal.com/.image/c_limit%2Ccs_srgb%2Cq_auto:good%2Cw_860/MTQ3MTU2NzMwOTA2NjgyODMw/2hp_290_1721_bjk.webp")
Pose.create(name:"Forward Fold", description:"Stand in Tadasana, hands on hips. Exhale and bend forward from the hip joints, not from the waist. As you descend draw the front torso out of the groins and open the space between the pubis and top sternum. As in all the forward bends, the emphasis is on lengthening the front torso as you move more fully into the position. If possible, with your knees straight, bring your palms or finger tips to the floor slightly in front of or beside your feet, or bring your palms to the backs of your ankles. If this isn't possible, cross your forearms and hold your elbows.", category: "Level 1", image:"https://www.yogajournal.com/.image/c_limit%2Ccs_srgb%2Cq_auto:good%2Cw_700/MTQ2MTgwNzIwNzk5NTI0Mzg0/hpforwardbend2.webp")
Pose.create(name:"Plow", description:"From lying position exhale and bend from the hip joints to slowly lower your toes to the floor above and beyond your head. As much as possible, keep your torso perpendicular to the floor and your legs fully extended.", category: "Level 1", image:"https://www.yogajournal.com/.image/c_limit%2Ccs_srgb%2Cq_auto:good%2Cw_450/MTQ2MTgwNzcyNjA1MzM5MTY4/plow-pose-halasana.webp")
Pose.create(name:"Triangle Pose", description:"Stand in Tadasana. With an exhalation, step or lightly jump your feet 3 1/2 to 4 feet apart. Raise your arms parallel to the floor and reach them actively out to the sides, shoulder blades wide, palms down. Turn your left foot in slightly to the right and your right foot out to the right 90 degrees. Align the right heel with the left heel. Exhale and extend your torso to the right directly over the plane of the right leg, bending from the hip joint, not the waist. Rest your right hand on your shin, ankle, or the floor outside your right foot, whatever is possible without distorting the sides of the torso. Stretch your left arm toward the ceiling", category: "Level 1", image:"https://www.yogajournal.com/.image/c_limit%2Ccs_srgb%2Cq_auto:good%2Cw_860/MTQ3MTc3OTY2Mjk4NzM2NDMx/2yp_285_1643_prf.webp")



